d,m = [int(i) for i in input().split()]
if(d==30 and m==12) : print("Donny")
elif(d==31 and m==10) : print("Donny")
elif(d==29 and m==11) : print("Donny")
elif(d==28 and m==9) : print("Donny")
elif(d==27 and m==8) : print("Donny")
elif(d==26 and m==7) : print("Donny")
elif(d==25 and m==6) : print("Donny")
elif(d==24 and m==5) : print("Donny")
elif(d==23 and m==4) : print("Donny")
elif(d==22 and m==3) : print("Donny")
elif(d==21 and m==2) : print("Donny")
elif(d==20 and m==1) : print("Donny")
else : print("Blanky")